---

- name: Ensure helm-diff plugin is installed
  become: true
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

# Add helm repos
- name: Ensure all necessary Helm repositories are present
  become: true
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    state: present
  loop: "{{ k3s_role_helm_repos }}"

- name: Ensure ingress-nginx Helm repository is present
  become: true
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx/
    state: present
  when: ingress_nginx_enabled | bool
