---

- name: Ensure helm-diff plugin is installed
  become: true
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present

# Add helm repos
- name: Ensure all necessary Helm repositories are present
  become: true
  kubernetes.core.helm_repository:
    name: "{{ item.name }}"
    repo_url: "{{ item.url }}"
    state: present
  loop: "{{ k3s_role_helm_repos }}"
