---
# Deploy add-ons via Helm
- name: Addons Deployment
  when: rfc2136_zone is defined and rfc2136_zone != ""
  become: true
  vars:
    external_dns_values_file: /root/external_dns_values.yaml
  block:
    # --- Namespace
    - name: Ensure external-dns namespace exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ external_dns_namespace }}"
        kubeconfig: "{{ kubeconfig_root }}"

    - name: Render external-dns Helm values file
      ansible.builtin.template:
        src: external_dns_values.yaml.j2
        dest: "{{ external_dns_values_file }}"
        owner: root
        group: root
        mode: "0600"

    - name: Install or upgrade External-DNS
      kubernetes.core.helm:
        name: external-dns
        chart_ref: external-dns/external-dns
        release_namespace: "{{ external_dns_namespace }}"
        kubeconfig: "{{ kubeconfig_root }}"
        state: present
        values_files: "{{ external_dns_values_file }}"
        wait: true
        atomic: true
