---
- name: Include preflight tasks
  ansible.builtin.include_tasks: 01_preflight.yml
  tags: [preflight, python]

- name: Include bootstrap tasks
  ansible.builtin.include_tasks: 02_bootstrap.yml
  tags: [bootstrap]

- name: Include network tasks
  ansible.builtin.include_tasks: 03_network.yml
  tags: [k3s, network]

- name: Include k3s install tasks
  ansible.builtin.include_tasks: 04_k3s_install.yml
  tags: [k3s]

- name: Include helm addons tasks
  ansible.builtin.include_tasks: 05_addons_helm.yml
  tags: [helm]
  when: k3s_role == 'server'

- name: Include ingress nginx addons tasks
  ansible.builtin.include_tasks: 06_addons_ingress_nginx.yml
  tags: [ingress]
  when: k3s_role == 'server' and ingress_nginx_enabled | bool

- name: Include cert manager addons tasks
  ansible.builtin.include_tasks: 07_addons_cert_manager.yml
  tags: [certmanager]
  when: k3s_role == 'server'

- name: Include external DNS addons tasks
  ansible.builtin.include_tasks: 08_addons_external_dns.yml
  tags: [externaldns]
  when: k3s_role == 'server'

- name: Include longhorn addon tasks
  ansible.builtin.include_tasks: 09_addons_longhorn.yml
  tags: [longhorn, storage]
  when: k3s_role == 'server' and longhorn_enabled | bool
